#
# Start-up General 
#
logger.info("#====================================================================================================#")
logger.info("   __      __          _____            __          __          ______           ____    ____     ___ ")
logger.info("  |   |   |   |     |   __   |         |   |       |   |       |   _   |         |   |   |   |   |   |")
logger.info("  |   |   |   |     |   | |  |         |   |       |   |       |  |  |  |        |   |   |   |   |   |")
logger.info("  |   |___|   |     |   | |  |         |   |       |   |       |  |   |  |         |_ |__| _|    |   |")
logger.info("  |    ___    |     |   | |  |         |   |   __  |   |       |  |    |  |          |    |      |   |")
logger.info("  |   |   |   |     |   | |  |         |   |  |  | |   |       |  |    | |           |    |      |___|")
logger.info("  |   |   |   |     |   |_|  |          |  |_| || ||  |        |  |___| |            |    |       ___ ")
logger.info("  |___|   |___|      |______ |           |____|  |___|         |_______|             |____|      |___|")
logger.info("")
logger.info("#====================================================================================================#")
logger.info("")
logger.info("        NexGenSnake: A Snakemake workflow for Variant Calling                                         ")
logger.info("          Author: Kyle Parker                                                                         ")
logger.info("          Github: Kxpark/NexGenSnake                                                                  ")
logger.info("          Version: 1.0                                                                                ")
logger.info("")
logger.info("     This work is supported by funding from the Agricultural Genome to Phenome Initiative (AG2PI)     ")
logger.info("                    which is funded by USDA-NIFA award 2022-70412-3845                                ")
logger.info("")
logger.info("")
logger.info("")
logger.info("       Please cite usage at https://doi.org/10.5281/zenodo.10702519                                   ")
logger.info("")
logger.info("")