#
# Start-up General 
#
logger.info("#====================================================================================================#")
logger.info("   __      __          _____            __          __          ______           ____    ____     ___ ")
logger.info("  |   |   |   |     /   __   \         |   |       |   |       |   _  \          |   |   |   |   |   |")
logger.info("  |   |   |   |     |   | |  |         |   |       |   |       |  |  \  \        \   |   |   |   |   |")
logger.info("  |   |___|   |     |   | |  |         |   |       |   |       |  |   \  \         \  \__/  /    |   |")
logger.info("  |    ___    |     |   | |  |         |   |   /\  |   |       |  |    |  |          |    |      |   |")
logger.info("  |   |   |   |     |   | |  |         \   |  /  \ |   /       |  |    / /           |    |      |___|")
logger.info("  |   |   |   |     |   |_|  |          \  \ / /\ \|  /        |  |___/ /            |    |       ___ ")
logger.info("  |___|   |___|      \______ /           \____/  \___/         |_______/             |____|      |___|")
logger.info("")
logger.info("#====================================================================================================#")
logger.info("")
logger.info("        NexGenSnake: A Snakemake workflow for Variant Calling                                         ")
logger.info("          Author: Kyle Parker                                                                         ")
logger.info("          Github: Kxpark/NexGenSnake                                                                  ")
logger.info("")
logger.info("     This work is supported by funding from the Agricultural Genome to Phenome Initiative (AG2PI)     ")
logger.info("                    which is funded by USDA-NIFA award 2022-70412-3845                                ")